package tech.kood.kmdb.model;

import java.time.LocalDate;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;

import jakarta.validation.constraints.*;

// JPA entity with id (primary and autogenerated), name, ad birthDay.
// Inverse side Many-to-Mayny relationship with Movie 
@Entity
public class Actor {
    private @Id @GeneratedValue Long id;

    @NotBlank(message = "name must not be blank")
    @Size(max = 120, message = "name must be at most 120 characters")
    private String name;

    @PastOrPresent(message = "birthDate must be in the past or today")
    private LocalDate birthDate;

    // Relationships - inverse side

    @ManyToMany(mappedBy = "actors")
    @JsonIgnoreProperties({ "actors", "genres" })
    Set<Movie> movies = new HashSet<>();

    public Actor() {}
    public Actor(String name, LocalDate birthDate) {
        this.name = name;
        this.birthDate = birthDate;
    }

    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public LocalDate getBirthDate() {
        return birthDate;
    }

    public void setBirthDate(LocalDate birthDate) {
        this.birthDate = birthDate;
    }

    // Getters & Setters for relationships
    
    public Set<Movie> getMovies() {
        return movies;
    }

    public void setMovies(Set<Movie> movies) {
        this.movies = movies;
    }
}
