package tech.kood.kmdb.model;

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;

import jakarta.validation.constraints.*;

// JPA entity with id (primary and autogenerated), and name.
// Inverse side Many-to-Mayny relationship with Movie 
@Entity
public class Genre {
    private @Id @GeneratedValue Long id;
    
    @NotBlank(message = "name must not be blank")
    @Size(max = 100, message = "name must be at most 100 characters")
    private String name;

    // Relationships - inverse side
    
    @ManyToMany(mappedBy = "genres")
    @JsonIgnoreProperties({ "genres", "actors" })
    private Set<Movie> movies = new HashSet<>();

    public Genre() {}
    public Genre(String name) {
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    // Getters & Setters for relationships
    
    public Set<Movie> getMovies() {
        return movies;
    }

    public void setMovies(Set<Movie> movies) {
        this.movies = movies;
    }
}
