package tech.kood.kmdb.model;

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;

import jakarta.validation.constraints.*;

// JPA entity with id (primary and autogenerated), title, releaseYear, and duration.
// Owner side Many-to-Mayny relationships with Genre and Actor. 
@Entity
public class Movie {
    private @Id @GeneratedValue Long id;

    @NotBlank(message = "title must not be blank")
    @Size(max = 200, message = "title must be at most 200 characters")
    private String title;
    
    @Min(value = 1888, message = "releaseYear must be >= 1888")
    @Max(value = 2100, message = "releaseYear must be <= 2100")
    private int releaseYear;
    
    
    @Min(value = 1, message = "duration must be >= 1")
    @Max(value = 600, message = "duration must be <= 600")
    private int duration;

    // Relationships

    // Movie-Genre
    @ManyToMany
    @JoinTable(
        name = "movie-genres",
        joinColumns = @JoinColumn(name = "movie_id"),
        inverseJoinColumns = @JoinColumn(name = "genre_id")
    )
    @JsonIgnoreProperties("movies")
    private Set<Genre> genres = new HashSet<>();

    // Movie-Actor
    @ManyToMany
    @JoinTable(
        name = "movie-actors",
        joinColumns = @JoinColumn(name = "movie_id"),
        inverseJoinColumns = @JoinColumn(name = "actor_id")
    )
    @JsonIgnoreProperties("movies")
    private Set<Actor> actors = new HashSet<>();

    public Movie() {}
    public Movie(String title, int releaseYear, int duration) {
        this.title = title;
        this.releaseYear = releaseYear;
        this.duration = duration;
    }

    public Long getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public int getReleaseYear() {
        return releaseYear;
    }

    public void setReleaseYear(int releaseYear) {
        this.releaseYear = releaseYear;
    }

    public int getDuration() {
        return duration;
    }

    public void setDuration(int duration) {
        this.duration = duration;
    }

    // Getters & Setters for relationships
    
    public Set<Genre> getGenres() {
        return genres;
    }

    public void setGenres(Set<Genre> genres) {
        this.genres = genres;
    }
    
    public Set<Actor> getActors() {
        return actors;
    }

    public void setActors(Set<Actor> actors) {
        this.actors = actors;
    }
}
